// Guided-lesson engine: turns repertoire trees into narrated walkthroughs.
// A unit references path prefixes in the tree; walks are generated by
// following OUR primary moves and the opponent's most-common replies, with
// sidelines split out at each opponent branch point.

import { Chess } from 'chess.js'
import type { RepNode, Repertoire } from '../data/openings/types'
import type { CourseUnit } from '../data/openings/courses'
import { childrenAt, nodeAt } from './repertoire'

export interface LessonStep {
  san: string
  /** e.g. "3...Bf5" */
  label: string
  ours: boolean
  note?: string
}

export interface LessonWalk {
  title: string
  steps: LessonStep[]
  /** SRS line key for the walk (repId + '/' + path). */
  key: string
}

function moveLabel(plyIndex: number, san: string): string {
  const moveNo = Math.floor(plyIndex / 2) + 1
  return plyIndex % 2 === 0 ? `${moveNo}.${san}` : `${moveNo}...${san}`
}

function stepsForPath(rep: Repertoire, path: string[]): LessonStep[] {
  return path.map((san, i) => {
    const node = nodeAt(rep, path.slice(0, i + 1))
    return {
      san,
      label: moveLabel(i, san),
      ours: (i % 2 === 0 ? 'w' : 'b') === rep.color,
      note: node?.note,
    }
  })
}

/** Extend a prefix to a leaf: our primary moves, opponent's top-weight replies. */
export function mainPathFrom(rep: Repertoire, prefix: string[]): string[] {
  const path = [...prefix]
  for (;;) {
    const options = childrenAt(rep, path)
    if (options.length === 0) return path
    const ourTurn = (path.length % 2 === 0 ? 'w' : 'b') === rep.color
    let next: RepNode | undefined
    if (ourTurn) {
      next = options.find((c) => c.primary) ?? options[0]
    } else {
      next = [...options].sort((a, b) => (b.weight ?? 1) - (a.weight ?? 1))[0]
    }
    path.push(next.san)
  }
}

/**
 * All walks for a unit: the main line of each declared path, plus sidelines
 * at opponent branch points inside the FIRST path's scope (weight-ordered,
 * capped so a lesson stays digestible).
 */
export function unitWalks(rep: Repertoire, unit: CourseUnit, maxSidelines = 3): LessonWalk[] {
  const walks: LessonWalk[] = []
  const seen = new Set<string>()
  const push = (title: string, path: string[]) => {
    const key = `${rep.id}/${path.join(' ')}`
    if (seen.has(key)) return
    seen.add(key)
    walks.push({ title, steps: stepsForPath(rep, path), key })
  }

  unit.paths.forEach((prefix, i) => {
    const full = mainPathFrom(rep, prefix)
    const tipSan = prefix[prefix.length - 1]
    push(i === 0 ? 'Main line' : `Line: ${moveLabel(prefix.length - 1, tipSan)}`, full)
  })

  // Sidelines inside the first path's subtree.
  const primaryPrefix = unit.paths[0]
  const mainPath = mainPathFrom(rep, primaryPrefix)
  const candidates: Array<{ at: string[]; alt: RepNode; depth: number }> = []
  for (let i = primaryPrefix.length; i < mainPath.length; i++) {
    const at = mainPath.slice(0, i)
    const ourTurn = (at.length % 2 === 0 ? 'w' : 'b') === rep.color
    if (ourTurn) continue
    const chosen = mainPath[i]
    for (const alt of childrenAt(rep, at)) {
      if (alt.san !== chosen) candidates.push({ at, alt, depth: i })
    }
  }
  candidates.sort((a, b) => (b.alt.weight ?? 1) - (a.alt.weight ?? 1) || a.depth - b.depth)
  for (const c of candidates.slice(0, maxSidelines)) {
    const path = mainPathFrom(rep, [...c.at, c.alt.san])
    push(`Sideline: ${moveLabel(c.at.length, c.alt.san)}${c.alt.name ? ` (${c.alt.name})` : ''}`, path)
  }
  return walks
}

/** FEN after the first `count` steps of a walk. Throws on illegal data (tests). */
export function fenAtStep(walk: LessonWalk, count: number): string {
  const game = new Chess()
  for (const step of walk.steps.slice(0, count)) game.move(step.san)
  return game.fen()
}

export function lastMoveAtStep(walk: LessonWalk, count: number): { from: string; to: string } | null {
  if (count === 0) return null
  const game = new Chess()
  let last: { from: string; to: string } | null = null
  for (const step of walk.steps.slice(0, count)) {
    const mv = game.move(step.san)
    last = { from: mv.from, to: mv.to }
  }
  return last
}
